databases:
  - name: app_render
    databaseName: app_render
    user: app_render

services:
  - type: web
    name: app_render
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_render
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false